services:
  accountservice:
    image: account-service
    container_name: AccountService
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    ports:
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=account_db;Username=postgres;Password=postgres;
      - Keycloak__ClientId=account-api
      - Keycloak__AuthorizationUrl=http://localhost:8080/realms/auth-service/protocol/openid-connect/auth
      - Keycloak__TokenUrl=http://keycloak:8080/realms/auth-service/protocol/openid-connect/token
      - Keycloak__MetadataAddress=http://keycloak:8080/realms/auth-service/.well-known/openid-configuration
      - Keycloak__ValidIssue=http://localhost:8080/realms/auth-service
      - TestUser__Username=tom
      - TestUser__Password=pass123
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2  
    container_name: Keycloak
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLE=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/realm-export.json:/opt/keycloak/data/import/realm.json  
    ports:
      - 8080:8080

  postgres:
    image: postgres:17
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: account_db
    volumes:
      - acc821_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: RabbitMQ
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - acc821_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
    acc821_postgres_data:
    acc821_rabbitmq_data: