services:
  accountservice:
    image: account-service
    container_name: AccountService
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    ports:
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=account_db;Username=postgres;Password=postgres;
      - Keycloak__ClientId=account-api
      - Keycloak__AuthorizationUrl=http://localhost:8080/realms/auth-service/protocol/openid-connect/auth
      - Keycloak__TokenUrl=http://keycloak:8080/realms/auth-service/protocol/openid-connect/token
      - Keycloak__MetadataAddress=http://keycloak:8080/realms/auth-service/.well-known/openid-configuration
      - Keycloak__ValidIssue=http://localhost:8080/realms/auth-service
      - TestUser__Username=tom
      - TestUser__Password=pass123
    depends_on:
      - postgres
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2  
    container_name: Keycloak
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLE=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./.containers:/opt/keykcloak/data       
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: account_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: