name: CI - AccountService

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore AccountService.sln

      - name: Build
        run: dotnet build AccountService.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test AccountService.sln --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"